### ISSUE TITLE
[Tests] Ethereum Bridge is crashing during tests.

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#178]
I have tracked this down all the way to a very initial commit on my part - f7e3efee1e76dc21435e2fb2af626775c2e6cf8f

#### to reproduce
1. start truffle
2. start eth-bridge
3. run full test suite
4. watch the crash occur 

```
[2018-12-18T23:46:58.161Z] INFO checking HTTP query 46a77f493f30332fb9dced0aa7a6a96c9c2d314bcdc9d963f9675620a5bc71e0 status on Tue Dec 18 2018 17:36:34 GMT-0700 (MST)
Error: Key not found in database
    at Object.InvalidResponse (/home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/errors.js:38:16)
    at RequestManager.send (/home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Eth.send [as getBlock] (/home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/method.js:145:58)
    at parseLog (/home/pelsasser/ethereum-bridge/lib/bridge-log-manager.js:130:59)
    at /home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/filter.js:120:21
    at Array.forEach (<anonymous>)
    at /home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/filter.js:119:32
    at Array.forEach (<anonymous>)
    at Object.onMessage [as callback] (/home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/filter.js:117:22)
    at /home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/requestmanager.js:259:20
    at Array.forEach (<anonymous>)
    at /home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/requestmanager.js:258:12
    at XMLHttpRequest.request.onreadystatechange (/home/pelsasser/ethereum-bridge/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/pelsasser/ethereum-bridge/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/pelsasser/ethereum-bridge/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/pelsasser/ethereum-bridge/node_modules/xhr2/lib/xhr2.js:509:12)
```

My best research at this point says there is some asynchronous issues that sometimes occurs (more often than not).  

Currently taking these steps to try and remedy
1. looking for any places `await` statements could be missing
1. ripping out all tests and starting from scratch

**Comment by pelsasser** [comment]
Confirmed 3c053644efbf9d5514d3d63282910d487c37becd was working prior to new contract structure.

**Comment by pelsasser** [comment]
was able to reproduce with OracleHubOraclize.js completely deleted.

**Comment by perfectmak** [comment]
I'll create the issue with eth-bridge now.
I'll also spend some time on this issue again today.

**Comment by pelsasser** [comment]
Completed!
