### ISSUE TITLE
[BUG] coverage tests fails in travis.

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#213]
#### Priority + Rationale
High - would like to see if we are actually missing any coverage

#### Describe the bug
https://travis-ci.org/MARKETProtocol/MARKETProtocol/builds/517388586?utm_source=github_status&utm_medium=notification

Tests pass, but coverage tests fail

#### Steps to Reproduce
See above

#### What do you believe the expected behavior is
coverage tests pass and we get reliable coverage info.

**Comment by pelsasser** [comment]
I am not sure this is currently worth fixing.  There are a few issues that are going to present themselves.

1. It appears that solidity-coverage is using an older version of ganache-cli than truffle is or some other oddity is causing different test behavior from the two
```
  1) Contract: MarketCollateralPool
       withdrawFees()
         should be able to withdraw mkt token fees:
     TypeError: finalReceipientBalance.minus is not a function
      at Context.<anonymous> (test/MarketCollateralPool.js:1058:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

  2) Contract: UpgradeableToken
       Main account should have entire balance:
     TypeError: mainAcctBalance.eq is not a function
```

2.  The `revert` errors in the coverage environment are not returning any sort of message with them.  Our new tests ensure the correct reason is return for the revert that we expect, and this doesn't occur in coverage.

Based on this, I think we may just want to ignore this issue for the time being.  Coverage when able to run locally is very very high at this point.

**Comment by pelsasser** [comment]
moving ethereumjs-testrpc-sc@6.4.1 helps, and locally I can get tests to run and coverage reported correctly without docker.

Looks like the issue with the failing tests is actually a result of .call() - I am going to commit fixes to the tests.

@perfectmak I could not get this working in CI with or without Docker, if you want to take a crack at it, please do.  Otherwise I think we should forego coverage for now.

**Comment by pelsasser** [comment]
```
--------------------------------------|----------|----------|----------|----------|----------------|
File                                  |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------------------|----------|----------|----------|----------|----------------|
 contracts/                           |    96.19 |       88 |      100 |    96.55 |                |
  MarketCollateralPool.sol            |      100 |       95 |      100 |      100 |                |
  MarketContract.sol                  |    90.48 |    77.78 |      100 |    90.48 |179,180,185,186 |
  MarketContractRegistry.sol          |      100 |    91.67 |      100 |      100 |                |
  MarketContractRegistryInterface.sol |      100 |      100 |      100 |      100 |                |
 contracts/libraries/                 |       88 |    76.32 |    95.24 |    84.95 |                |
  MathLib.sol                         |    95.12 |    82.14 |    92.86 |    95.12 |          68,77 |
  StringLib.sol                       |    79.41 |       60 |      100 |    76.92 |... 133,134,138 |
 contracts/mpx/                       |     91.3 |       80 |    88.89 |    91.67 |                |
  MarketContractFactoryMPX.sol        |      100 |      100 |      100 |      100 |                |
  MarketContractMPX.sol               |    85.71 |    66.67 |       80 |    86.67 |          97,98 |
 contracts/tokens/                    |      100 |      100 |      100 |      100 |                |
  MarketToken.sol                     |      100 |      100 |      100 |      100 |                |
  PositionToken.sol                   |      100 |      100 |      100 |      100 |                |
  UpgradableToken.sol                 |      100 |      100 |      100 |      100 |                |
  UpgradeableTarget.sol               |      100 |      100 |      100 |      100 |                |
--------------------------------------|----------|----------|----------|----------|----------------|
All files                             |    93.06 |       83 |    96.55 |    91.87 |                |
--------------------------------------|----------|----------|----------|----------|----------------|
```
