### ISSUE TITLE
Bootstrapping new environment, import not found in MarketCollateralPool.sol

### ISSUE THREAD

**Issue by rspurgeon** [MARKETProtocol/MARKETProtocol#56]
Following instructions in the MARKETProtocol README: https://github.com/MARKETProtocol/MARKETProtocol

From the truffle prompt:

```
truffle(develop)> migrate
Error: Could not find zeppelin-solidity/contracts/token/SafeERC20.sol from any sources; imported from /home/rspurgeon/dev/github/market/MARKETProtocol/contracts/MarketCollateralPool.sol
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:76:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/onlyOnce.js:12:1
    at next (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/whilst.js:68:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:64:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/fs.js:85:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/once.js:12:1
    at replenish (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/eachOfLimit.js:59:1)
    at iterateeCallback (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/eachOfLimit.js:49:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/onlyOnce.js:12:1
    at ReadFileContext.callback (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/fs.js:81:1)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
```

The zeppelin-solidity module listing shows the below which doesn't appear to match the import statement in CollateralToken.sol:24

```
(master)|~/dev/github/market/MARKETProtocol> ll node_modules/zeppelin-solidity/contracts/token/
total 4.0K
drwxr-xr-x. 2 rspurgeon  <> 4.0K Mar 12 13:02 ERC20
drwxr-xr-x. 2 rspurgeon <> 45 Mar 12 13:02 ERC721
drwxr-xr-x. 2 rspurgeon <>  45 Mar 12 13:02 ERC827
```

npm view shows:
` dependencies: { truffle: '^4.0.1', 'zeppelin-solidity': '^1.5.0' },`

**Comment by pelsasser** [comment]
@rspurgeon looks like 'zeppelin-solidity' has update their package structure.  Shows me, I guess I should have been explicit in the npm version ;) .  I will address this today.  Thanks for the heads up!

**Comment by pelsasser** [comment]
@rspurgeon try pulling now, and then `npm install` and see where you end up - I think this should be good now.

**Comment by rspurgeon** [comment]
I can get past the previous step, but I'm getting the below errors in the the testing system. 

```
truffle(develop)> test
Using network 'develop'.

Compiling ./contracts/Creatable.sol...
Compiling ./contracts/libraries/MathLib.sol...
Compiling ./contracts/libraries/OrderLib.sol...
Compiling ./contracts/tokens/MarketToken.sol...
Compiling ./test/TestCreatable.sol...
Compiling ./test/libraries/TestMathLib.sol...
Compiling ./test/libraries/TestOrderLib.sol...
Compiling ./test/tokens/TestMarketToken.sol...
Compiling truffle/Assert.sol...
Compiling zeppelin-solidity/contracts/math/SafeMath.sol...
Compiling zeppelin-solidity/contracts/token/BasicToken.sol...
Compiling zeppelin-solidity/contracts/token/ERC20.sol...
Compiling zeppelin-solidity/contracts/token/ERC20Basic.sol...
Compiling zeppelin-solidity/contracts/token/StandardToken.sol...
/home/rspurgeon/dev/github/market/MARKETProtocol/test/GasOraclize.js:19
    before(async function() {
           ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/usr/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:514:10)
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/lib/test.js:125:1
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
truffle(develop)>

```

**Comment by pelsasser** [comment]
@rspurgeon I think this is due to an older version of node and it not supporting async functions.

What version are you running?

```
~/MARKETProtocol$ node --version
v8.10.0
```

**Comment by rspurgeon** [comment]
Yes, i'm wayy out of date (Centos is good like that).  I'll upgrade and try again

**Comment by rspurgeon** [comment]
For safe keeping for anyone having issues upgrading node from earlier versions on Centos.
https://github.com/nodesource/distributions/issues/191

**Comment by pelsasser** [comment]
@rspurgeon let me know how it goes once you updated.

**Comment by rspurgeon** [comment]
I haven't been able to re-test on the Centos host yet, but tests pass on the Mac 'out of the box'

**Comment by pelsasser** [comment]
@rspurgeon can I close this? any pending problems?
